name: nginx-1.28
on:
  push:
    branches: ["main"]
    paths:
      - "stable/1.28/**"
  schedule:
    - cron: "0 8 * * 0"
  workflow_dispatch:

env:
  NAME: "nginx"
  MILESTONE: "1.28"
  NGX_VER: "1.28.1"
  REGISTRY: ghcr.io

jobs:
  build-alpine-slim:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        alpine-version: ["3.21", "3.23"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push "alpine-slim"
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./stable/${{ env.MILESTONE }}/alpine-slim
          push: true
          build-args: |
            AVER=${{ matrix.alpine-version }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.NAME }}:${{ env.NGX_VER }}-alpine${{ matrix.alpine-version }}-slim

  build-alpine:
    needs: build-alpine-slim
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        alpine-version: ["3.21", "3.23"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push "alpine"
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./stable/${{ env.MILESTONE }}/alpine
          push: true
          build-args: |
            AVER=${{ matrix.alpine-version }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.NAME }}:${{ env.NGX_VER }}-alpine${{ matrix.alpine-version }}${{ matrix.alpine-version == '3.23' && format(',{0}/{1}/{2}:latest', env.REGISTRY, github.repository_owner, env.NAME) || '' }}

  build-alpine-perl:
    needs: build-alpine
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        alpine-version: ["3.21", "3.23"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push "alpine-perl"
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./stable/${{ env.MILESTONE }}/alpine-perl
          push: true
          build-args: |
            AVER=${{ matrix.alpine-version }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.NAME }}:${{ env.NGX_VER }}-alpine${{ matrix.alpine-version }}-perl

  build-alpine-otel:
    needs: build-alpine
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        alpine-version: ["3.21", "3.23"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push "alpine-otel"
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./stable/${{ env.MILESTONE }}/alpine-otel
          push: true
          build-args: |
            AVER=${{ matrix.alpine-version }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.NAME }}:${{ env.NGX_VER }}-alpine${{ matrix.alpine-version }}-otel
